- name: Generate CycloneDX SBOM
        run: |
          ./gradlew :app:cyclonedxBom
          # Output: app/build/reports/bom.json

      - name: Generate SPDX SBOM
        uses: CycloneDX/gh-node-module-generatebom@v1
        with:
          path: ./app
          output: sbom-spdx.json